Initial migration of bulk extractor to OpenRelik
openrelik/openrelik-worker-bulkextractor pull request #1
Opened 2024-12-18 00:15 UTC by axpatito

This PR is meant to provide the first migration of Turbinia's workflow bulk extractor to OpenRelik. Debug flags are still on and the worker hasn't been added to the main docker-compose file.

2024-12-24 22:15 UTC, berggren requested changes
Overall looks good! Please tale a look at my comment on the reporting. We have this functionality in the common lib and you will get a bunch of stuff for free.

2024-12-24 22:15 UTC, berggren commented on Dockerfile
> +    bulk-extractor \
What version of BE is in the apt repository? 1.x or 2.x?

2024-12-24 22:15 UTC, berggren commented on Dockerfile
> +# CMD ["celery", "--app=src.tasks", "worker", "--task-events", "--concurrency=1", "--loglevel=INFO"]
Remove?

2024-12-24 22:15 UTC, berggren commented on src/tasks.py
> +from .text_formatter import heading4,heading5,bullet
In the openrelik-worker-common lib we have markdown report functionality already. Please take a look here: https://github.com/openrelik/openrelik-worker-common/blob/main/openrelik_worker_common/reporting.py

And an example of using it in another worker: https://github.com/openrelik/openrelik-worker-analyzer-config/blob/609f5cebb440cb01d56d19d892bf8408f39a6b6f/src/analyzers/sshd_analyzer.py#L32

Let's use that instead to stay consitent and also, if you create a "task report" using it you will get some UI things for free as well :)

2025-01-06 23:57 UTC, axpatito commented on Dockerfile
> +    bulk-extractor \
```
bulk_extractor --version
bulk_extractor 2.1.1
```

2025-01-06 23:57 UTC, axpatito commented on Dockerfile
> +# CMD ["celery", "--app=src.tasks", "worker", "--task-events", "--concurrency=1", "--loglevel=INFO"]
Done

2025-01-06 23:57 UTC, axpatito commented on src/tasks.py
> +from .text_formatter import heading4,heading5,bullet
Done

2025-01-09 19:43 UTC, berggren requested changes
Looks good, a few comments to address.

2025-01-09 19:43 UTC, berggren commented on src/tasks.py
> +        #    f'Error parsing feature from Bulk Extractor report: {exception!s}')
```suggestion
```

2025-01-09 19:43 UTC, berggren commented on src/tasks.py
> +                    with open(out_file.path, "wb") as out_f:
Could we just move the file instead of read/write to the new location?

2025-01-09 19:43 UTC, berggren commented on src/tasks.py
> +            display_name="Report_{}".format(input_file.get("display_name")),
For consitency, use f strings:

```suggestion
            display_name=f"Report_{input_file.get("display_name")}.html",
```

2025-01-09 19:43 UTC, berggren commented on src/tasks.py
> +            data_type="html",
We can skip these two, use the default data_type (we will change this in the near future) and we set the extension on the display_name above
```suggestion
```

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +                    with open(out_file.path, "wb") as out_f:
I would need to convert it into OuputFile which IMO requires a new function in common for these types of cases (a tool outputs a file and we need that file available). I wasn't able to solve this. Any suggestions?

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +    out_dir = os.path.join(artifact_dir, "output")
Done

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +        #    f'Error parsing feature from Bulk Extractor report: {exception!s}')
Done

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +            display_name="Report_{}".format(input_file.get("display_name")),
Done

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +            data_type="html",
Done

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
>          output_file = create_output_file(
Done

2025-01-10 23:56 UTC, axpatito commented on src/tasks.py
> +        artifacts_dir = os.path.join(output_path, uuid4().hex)
Done

2025-01-17 09:51 UTC, hacktobeer commented
@berggren Can you address the changes on your comments? When done I will do a final review and merge.

2025-01-17 11:01 UTC, berggren commented on src/tasks.py
> +                    with open(out_file.path, "wb") as out_f:
Yeah, you are right. All good with the current solution

2025-01-17 11:06 UTC, berggren commented on src/tasks.py
> +            section.add_table(t)
```suggestion
            table = MarkdownTable(columns)
            for scanner_result in sorted_scanner_results:
                table.add_row([str(scanner_result[column]) for column in columns])
            section.add_table(table)
```

2025-01-17 11:10 UTC, berggren commented on src/tasks.py
> +        shutil.rmtree(tmp_artifacts_dir)
```suggestion
        if os.path.exists(tmp_artifacts_dir):
            shutil.rmtree(tmp_artifacts_dir)
```

2025-01-17 11:12 UTC, berggren commented
> @berggren Can you address the changes on your comments? When done I will do a final review and merge.

Done. Looks good overall. I have not tested running it, consider doing before merge.

2025-01-17 16:12 UTC, jleaniz commented
Drive by comment - please write unit tests when you have a chance.

2025-01-23 10:51 UTC, hacktobeer commented
@axpatito I am ready to merge this when unit tests have been added. Can you add those?

2025-01-23 10:52 UTC, hacktobeer requested changes
LGTM except for missing unit tests.

2025-01-23 17:07 UTC, axpatito commented
Tests were added in #2

2025-01-23 20:55 UTC, berggren commented
> Tests were added in #2

Excellent, merging this one 🎉

2025-01-23 20:56 UTC, merged